### ISSUE TITLE
Intermittent failure in servstate tests

### ISSUE THREAD

**Issue by barrettj12** [canonical/pebble#224]
```
panic: internal error: reaper must be started

goroutine 275 [running]:
github.com/canonical/pebble/internal/reaper.WaitCommand(0xc000292b00, 0xc000044708, 0x7f2824, 0xb8c1e8)
	/home/runner/work/pebble/pebble/internal/reaper/reaper.go:192 +0x794
github.com/canonical/pebble/internal/overlord/servstate.(*serviceData).startInternal.func2(0xc000292b00, 0xc000353a10, 0x5, 0xc0000830e0, 0xc0000ddb80)
	/home/runner/work/pebble/pebble/internal/overlord/servstate/handlers.go:414 +0x51
created by github.com/canonical/pebble/internal/overlord/servstate.(*serviceData).startInternal
	/home/runner/work/pebble/pebble/internal/overlord/servstate/handlers.go:413 +0x111e
FAIL	github.com/canonical/pebble/internal/overlord/servstate	2.850s
```

See the full test logs [here](https://github.com/canonical/pebble/actions/runs/5020872866/jobs/9002731241?pr=221).

I can't quite tell from the logs which test is failing.

**Comment by barrettj12** [comment]
Still observing this [here](https://github.com/canonical/pebble/actions/runs/5459284932/jobs/9935129193?pr=218).

**Comment by flotter** [comment]
@barrettj12 Hi Jordan, yes, I will tackle servstate next ...

**Comment by flotter** [comment]
https://github.com/canonical/pebble/pull/266 Should now fix this.
