### ISSUE TITLE
panic on autostart with multi-lanes scenario

### ISSUE THREAD

**Issue by hemanthnakkina** [canonical/pebble#525]
Summary:
Deploying an application with pebble plan having multi-lane gets pebble to panic mode.

Environment: juju 3.6 + microk8s 1.28-strict/stable
Note: The problem is not observed with juju 3.5 since juju 3.5 uses pebble 1.10.2 where as juju 3.6 moved to pebble 1.16.0
Layer definition looks like: https://github.com/openstack-charmers/charm-rabbitmq-k8s/blob/ce7737e6a39700abcdbd038e5f0cbef47bc4e90b/src/charm.py#L283

Reproducer:
```
juju add-model test
juju deploy ch:rabbitmq-k8s --channel 3.12/edge --revision 38 --config minimum-replicas=1 --trust rabbitmq
```

Panic output:
```
2024-11-27T02:53:04.103Z [pebble] HTTP API server listening on ":38813".
2024-11-27T02:53:04.103Z [pebble] Started daemon.
2024-11-27T02:53:05.032Z [pebble] GET /v1/services?names=rabbitmq 71.434µs 200
2024-11-27T02:53:05.061Z [pebble] GET /v1/files?action=list&path=%2Fvar%2Flib%2Frabbitmq&itself=true 355.8µs 200
2024-11-27T02:53:05.077Z [pebble] POST /v1/files 8.226626ms 200
2024-11-27T02:53:05.091Z [pebble] POST /v1/files 8.21582ms 200
2024-11-27T02:53:05.104Z [pebble] POST /v1/files 6.399553ms 200
2024-11-27T02:53:05.113Z [pebble] GET /v1/files?action=read&path=%2Fusr%2Fbin%2Fnotifier 160.471µs 200
2024-11-27T02:53:05.131Z [pebble] POST /v1/files 7.820753ms 200
2024-11-27T02:53:05.154Z [pebble] POST /v1/layers 343.026µs 200
2024-11-27T02:53:05.155Z [pebble] GET /v1/services?names=rabbitmq 144.932µs 200
panic: runtime error: index out of range [1] with length 1

goroutine 53 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:26 +0x5e
github.com/canonical/pebble/internals/daemon.(*Daemon).Start.exitOnPanic.func5.1()
	/home/jenkins/workspace/build-juju/build/src/github.com/juju/juju/vendor/github.com/canonical/pebble/internals/daemon/daemon.go:338 +0x54
panic({0x8768a0?, 0xc0004221f8?})
	/usr/local/go/src/runtime/panic.go:785 +0x132
github.com/canonical/pebble/internals/plan.createLanes({0xc00041e540, 0x3, 0x3?}, 0xc000416ab0)
	/home/jenkins/workspace/build-juju/build/src/github.com/juju/juju/vendor/github.com/canonical/pebble/internals/plan/plan.go:999 +0x365
github.com/canonical/pebble/internals/plan.(*Plan).StartOrder(0xc000416b40, {0xc00041e500?, 0xc0002ef250?, 0x805680?})
	/home/jenkins/workspace/build-juju/build/src/github.com/juju/juju/vendor/github.com/canonical/pebble/internals/plan/plan.go:933 +0x46
github.com/canonical/pebble/internals/overlord/servstate.(*ServiceManager).DefaultServiceNames(0xc000420dc0?)
	/home/jenkins/workspace/build-juju/build/src/github.com/juju/juju/vendor/github.com/canonical/pebble/internals/overlord/servstate/manager.go:207 +0x1a5
github.com/canonical/pebble/internals/daemon.v1PostServices(0xbf5c80, 0xc000420c80, 0xc00040a330?)
	/home/jenkins/workspace/build-juju/build/src/github.com/juju/juju/vendor/github.com/canonical/pebble/internals/daemon/api_services.go:84 +0x2d1
github.com/canonical/pebble/internals/daemon.(*Command).ServeHTTP(0xbf5c80, {0x95c628, 0xc00040a318}, 0xc000420c80)
	/home/jenkins/workspace/build-juju/build/src/github.com/juju/juju/vendor/github.com/canonical/pebble/internals/daemon/daemon.go:238 +0x368
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000b6180, {0x95c628, 0xc00040a318}, 0xc000420a00)
	/home/jenkins/workspace/build-juju/build/src/github.com/juju/juju/vendor/github.com/gorilla/mux/mux.go:212 +0x1e2
github.com/canonical/pebble/internals/daemon.(*Daemon).Start.logit.func4({0x95c880, 0xc0004281c0}, 0xc000420a00)
	/home/jenkins/workspace/build-juju/build/src/github.com/juju/juju/vendor/github.com/canonical/pebble/internals/daemon/daemon.go:304 +0xd2
net/http.HandlerFunc.ServeHTTP(0x7ad043?, {0x95c880?, 0xc0004281c0?}, 0xc0002b4b40?)
	/usr/local/go/src/net/http/server.go:2220 +0x29
github.com/canonical/pebble/internals/daemon.(*Daemon).Start.exitOnPanic.func5({0x95c880?, 0xc0004281c0?}, 0x0?)
	/home/jenkins/workspace/build-juju/build/src/github.com/juju/juju/vendor/github.com/canonical/pebble/internals/daemon/daemon.go:342 +0x78
net/http.HandlerFunc.ServeHTTP(0x40d665?, {0x95c880?, 0xc0004281c0?}, 0xc000428101?)
	/usr/local/go/src/net/http/server.go:2220 +0x29
net/http.serverHandler.ServeHTTP({0x95b3a8?}, {0x95c880?, 0xc0004281c0?}, 0x6?)
	/usr/local/go/src/net/http/server.go:3210 +0x8e
net/http.(*conn).serve(0xc00040e510, {0x95cd40, 0xc0001f30e0})
	/usr/local/go/src/net/http/server.go:2092 +0x5d0
created by net/http.(*Server).Serve in goroutine 20
	/usr/local/go/src/net/http/server.go:3360 +0x485
```

After charm debugging, seems like this happened when autostart API is called to pebble.

Simple reproducer using pebble unit tests:
Patch to be applied on master:
```
diff --git a/internals/plan/plan_test.go b/internals/plan/plan_test.go
index 000e0c3..22a8f38 100644
--- a/internals/plan/plan_test.go
+++ b/internals/plan/plan_test.go
@@ -2050,6 +2050,7 @@ func (s *S) TestStartStopOrderMultipleLanes(c *C) {
                                Override: "replace",
                                Command:  `cmd`,
                                Startup:  plan.StartupEnabled,
+                               Requires: []string{"srv1"},
                        },
                },
                Checks:     map[string]*plan.Check{},
```

Unit test output:
```
$ go test ./internals/plan -v -check.v -check.f TestStartStopOrderMultipleLanes
=== RUN   Test

----------------------------------------------------------------------
PANIC: plan_test.go:2031: S.TestStartStopOrderMultipleLanes

... Panic: runtime error: index out of range [1] with length 1 (PC=0x43DC71)

/snap/go/10744/src/runtime/panic.go:770
  in gopanic
/snap/go/10744/src/runtime/panic.go:114
  in goPanicIndex
plan.go:1152
  in createLanes
plan.go:1086
  in Plan.StartOrder
plan_test.go:2062
  in S.TestStartStopOrderMultipleLanes
/snap/go/10744/src/reflect/value.go:380
  in Value.Call
/snap/go/10744/src/runtime/asm_amd64.s:1695
  in goexit
OOPS: 0 passed, 1 PANICKED
--- FAIL: Test (0.00s)
FAIL
FAIL	github.com/canonical/pebble/internals/plan	0.004s
FAIL
```

**Comment by benhoyt** [comment]
Thanks for the report -- @IronCore864 will look at this, and hopefully we can fix before we push the next release tomorrow.

**Comment by IronCore864** [comment]
@hemanthnakkina Thanks for raising this issue. I had a quick look, and I believe there is a bug when creating lanes for multiple services defined in a random order.

I will provide a quick fix with a unit test covering this case, which will be shipped in the next release.
